cnit_snappy_pdf_homepage:
    path:     /hello/{name}
    defaults: { _controller: CnitSnappyPDFBundle:Default:index }

cnit_snappy_pdf_pdf:
    pattern: /cnit/snappy/pdf
    defaults: { _controller: CnitSnappyPDFBundle:Default:snappyPdf }
